export const SHOP_ACTION_TYPES = {
   // SET_CATEGORIES: 'SET_CATEGORIES',
   FETCH_CATEGORIES_START: 'shop/FETCH_CATEGORIES_START',
   FETCH_CATEGORIES_SUCCESS: 'shop/FETCH_CATEGORIES_SUCCESS',
   FETCH_CATEGORIES_FAILURE: 'shop/FETCH_CATEGORIES_FAILURE',
}